### ISSUE TITLE
Change the links from appsdeck to scalingo

### ISSUE THREAD

**Issue by annemarie35** [Scalingo/sample-python-flask#1]
Hi there,
I'm trying to ship a little flask application to scalingo using this example. I've noticed that you still are using appsdeck in the readme. 
I also had to create a dsa key for my scalingo account before all  :)

Maybe i could update the readme for you  ?

Anyway, I still can't ship my app to scalingo,  I keep searching (i'm a newbie programmer...)
Cheers !
Anne-Marie

**Comment by Soulou** [comment]
I've modified the README, sorry for this omission, I invite you to contact us at support@scalingo.com to have details if you encounter difficulies in deploying an application. (I close the issue know, reopen if needed)

**Comment by annemarie35** [comment]
Thanks a lot !
